# Project context (helps AI understand your domain)
project:
  name: "My Project" # Change this to your project name
  description: "Brief description of your project for better translations"
  # domain: "web-app"  # Optional: e-commerce, healthcare, travel, etc.

# Files configuration
files:
  # Change this to your translation files directory
  directory: "locales"
  # Map file names to locale codes (BCP 47 format required)
  locales:
    "en.json": "en-US"
    # "fr.json": "fr-FR"
    # "es.json": "es-ES"
    # "de.json": "de-DE"
  # indent: 2 # (optional, defaults to 2)

# Translation providers configuration
providers:
  # Which provider to use (e.g., "openai", "claude", "deepl")
  # Remember to set the matching API key in your environment (e.g., DIRE_OPENAI_API_KEY, DIRE_CLAUDE_API_KEY, DIRE_DEEPL_API_KEY).
  active: "openai"
  # Define LLM providers you want to have available
  configuration:
    - name: "openai"
      model: "gpt-4.1-nano"
      maxTokens: 32000
      temperature: 0.2
    # - name: "claude"
    #   model: "claude-3-5-haiku-latest"
    #   maxTokens: 8192
    #   temperature: 0.2
    # - name: "gemini"
    #   model: "gemini-1.5-flash"
    #   maxTokens: 32000
    #   temperature: 0.2
    # - name: "mistral"
    #   model: "mistral-small-latest"
    #   maxTokens: 32000
    #   temperature: 0.2
    # - name: "deepseek"
    #   model: "deepseek-chat"
    #   maxTokens: 8192
    #   temperature: 0.2

# Style guide configuration (optional)
# styleGuide:
#   formality: "automatic"  # automatic | formal | informal

# Glossary for consistent translations (optional)
# Define specific terms that should be translated consistently
# glossary:
#   autoSort: true  # Automatically sort glossary entries alphabetically (primary locale/order taken from the first entry's key order)
#   entries:
#     - { en-US: "dashboard", fr-FR: "tableau de bord", es-ES: "panel de control" }
#     - { en-US: "user", fr-FR: "utilisateur", es-ES: "usuario" }
#     - { en-US: "API", fr-FR: "API", es-ES: "API" }
